// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package rdb

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// BoardsSectionsPosition is an object representing the database table.
type BoardsSectionsPosition struct {
	ID        uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	BoardID   uint      `boil:"board_id" json:"board_id" toml:"board_id" yaml:"board_id"`
	SectionID uint      `boil:"section_id" json:"section_id" toml:"section_id" yaml:"section_id"`
	Position  uint      `boil:"position" json:"position" toml:"position" yaml:"position"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *boardsSectionsPositionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L boardsSectionsPositionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BoardsSectionsPositionColumns = struct {
	ID        string
	BoardID   string
	SectionID string
	Position  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	BoardID:   "board_id",
	SectionID: "section_id",
	Position:  "position",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

var BoardsSectionsPositionWhere = struct {
	ID        whereHelperuint
	BoardID   whereHelperuint
	SectionID whereHelperuint
	Position  whereHelperuint
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperuint{field: "`boards_sections_positions`.`id`"},
	BoardID:   whereHelperuint{field: "`boards_sections_positions`.`board_id`"},
	SectionID: whereHelperuint{field: "`boards_sections_positions`.`section_id`"},
	Position:  whereHelperuint{field: "`boards_sections_positions`.`position`"},
	CreatedAt: whereHelpernull_Time{field: "`boards_sections_positions`.`created_at`"},
	UpdatedAt: whereHelpernull_Time{field: "`boards_sections_positions`.`updated_at`"},
}

// BoardsSectionsPositionRels is where relationship names are stored.
var BoardsSectionsPositionRels = struct {
	Board   string
	Section string
}{
	Board:   "Board",
	Section: "Section",
}

// boardsSectionsPositionR is where relationships are stored.
type boardsSectionsPositionR struct {
	Board   *Board
	Section *Section
}

// NewStruct creates a new relationship struct
func (*boardsSectionsPositionR) NewStruct() *boardsSectionsPositionR {
	return &boardsSectionsPositionR{}
}

// boardsSectionsPositionL is where Load methods for each relationship are stored.
type boardsSectionsPositionL struct{}

var (
	boardsSectionsPositionAllColumns            = []string{"id", "board_id", "section_id", "position", "created_at", "updated_at"}
	boardsSectionsPositionColumnsWithoutDefault = []string{"board_id", "section_id", "position"}
	boardsSectionsPositionColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	boardsSectionsPositionPrimaryKeyColumns     = []string{"id"}
)

type (
	// BoardsSectionsPositionSlice is an alias for a slice of pointers to BoardsSectionsPosition.
	// This should generally be used opposed to []BoardsSectionsPosition.
	BoardsSectionsPositionSlice []*BoardsSectionsPosition
	// BoardsSectionsPositionHook is the signature for custom BoardsSectionsPosition hook methods
	BoardsSectionsPositionHook func(context.Context, boil.ContextExecutor, *BoardsSectionsPosition) error

	boardsSectionsPositionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	boardsSectionsPositionType                 = reflect.TypeOf(&BoardsSectionsPosition{})
	boardsSectionsPositionMapping              = queries.MakeStructMapping(boardsSectionsPositionType)
	boardsSectionsPositionPrimaryKeyMapping, _ = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, boardsSectionsPositionPrimaryKeyColumns)
	boardsSectionsPositionInsertCacheMut       sync.RWMutex
	boardsSectionsPositionInsertCache          = make(map[string]insertCache)
	boardsSectionsPositionUpdateCacheMut       sync.RWMutex
	boardsSectionsPositionUpdateCache          = make(map[string]updateCache)
	boardsSectionsPositionUpsertCacheMut       sync.RWMutex
	boardsSectionsPositionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var boardsSectionsPositionBeforeInsertHooks []BoardsSectionsPositionHook
var boardsSectionsPositionBeforeUpdateHooks []BoardsSectionsPositionHook
var boardsSectionsPositionBeforeDeleteHooks []BoardsSectionsPositionHook
var boardsSectionsPositionBeforeUpsertHooks []BoardsSectionsPositionHook

var boardsSectionsPositionAfterInsertHooks []BoardsSectionsPositionHook
var boardsSectionsPositionAfterSelectHooks []BoardsSectionsPositionHook
var boardsSectionsPositionAfterUpdateHooks []BoardsSectionsPositionHook
var boardsSectionsPositionAfterDeleteHooks []BoardsSectionsPositionHook
var boardsSectionsPositionAfterUpsertHooks []BoardsSectionsPositionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BoardsSectionsPosition) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BoardsSectionsPosition) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BoardsSectionsPosition) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BoardsSectionsPosition) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BoardsSectionsPosition) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BoardsSectionsPosition) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BoardsSectionsPosition) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BoardsSectionsPosition) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BoardsSectionsPosition) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range boardsSectionsPositionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBoardsSectionsPositionHook registers your hook function for all future operations.
func AddBoardsSectionsPositionHook(hookPoint boil.HookPoint, boardsSectionsPositionHook BoardsSectionsPositionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		boardsSectionsPositionBeforeInsertHooks = append(boardsSectionsPositionBeforeInsertHooks, boardsSectionsPositionHook)
	case boil.BeforeUpdateHook:
		boardsSectionsPositionBeforeUpdateHooks = append(boardsSectionsPositionBeforeUpdateHooks, boardsSectionsPositionHook)
	case boil.BeforeDeleteHook:
		boardsSectionsPositionBeforeDeleteHooks = append(boardsSectionsPositionBeforeDeleteHooks, boardsSectionsPositionHook)
	case boil.BeforeUpsertHook:
		boardsSectionsPositionBeforeUpsertHooks = append(boardsSectionsPositionBeforeUpsertHooks, boardsSectionsPositionHook)
	case boil.AfterInsertHook:
		boardsSectionsPositionAfterInsertHooks = append(boardsSectionsPositionAfterInsertHooks, boardsSectionsPositionHook)
	case boil.AfterSelectHook:
		boardsSectionsPositionAfterSelectHooks = append(boardsSectionsPositionAfterSelectHooks, boardsSectionsPositionHook)
	case boil.AfterUpdateHook:
		boardsSectionsPositionAfterUpdateHooks = append(boardsSectionsPositionAfterUpdateHooks, boardsSectionsPositionHook)
	case boil.AfterDeleteHook:
		boardsSectionsPositionAfterDeleteHooks = append(boardsSectionsPositionAfterDeleteHooks, boardsSectionsPositionHook)
	case boil.AfterUpsertHook:
		boardsSectionsPositionAfterUpsertHooks = append(boardsSectionsPositionAfterUpsertHooks, boardsSectionsPositionHook)
	}
}

// One returns a single boardsSectionsPosition record from the query.
func (q boardsSectionsPositionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BoardsSectionsPosition, error) {
	o := &BoardsSectionsPosition{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "rdb: failed to execute a one query for boards_sections_positions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all BoardsSectionsPosition records from the query.
func (q boardsSectionsPositionQuery) All(ctx context.Context, exec boil.ContextExecutor) (BoardsSectionsPositionSlice, error) {
	var o []*BoardsSectionsPosition

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "rdb: failed to assign all query results to BoardsSectionsPosition slice")
	}

	if len(boardsSectionsPositionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all BoardsSectionsPosition records in the query.
func (q boardsSectionsPositionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to count boards_sections_positions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q boardsSectionsPositionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "rdb: failed to check if boards_sections_positions exists")
	}

	return count > 0, nil
}

// Board pointed to by the foreign key.
func (o *BoardsSectionsPosition) Board(mods ...qm.QueryMod) boardQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.BoardID),
	}

	queryMods = append(queryMods, mods...)

	query := Boards(queryMods...)
	queries.SetFrom(query.Query, "`boards`")

	return query
}

// Section pointed to by the foreign key.
func (o *BoardsSectionsPosition) Section(mods ...qm.QueryMod) sectionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.SectionID),
	}

	queryMods = append(queryMods, mods...)

	query := Sections(queryMods...)
	queries.SetFrom(query.Query, "`sections`")

	return query
}

// LoadBoard allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (boardsSectionsPositionL) LoadBoard(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoardsSectionsPosition interface{}, mods queries.Applicator) error {
	var slice []*BoardsSectionsPosition
	var object *BoardsSectionsPosition

	if singular {
		object = maybeBoardsSectionsPosition.(*BoardsSectionsPosition)
	} else {
		slice = *maybeBoardsSectionsPosition.(*[]*BoardsSectionsPosition)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &boardsSectionsPositionR{}
		}
		args = append(args, object.BoardID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardsSectionsPositionR{}
			}

			for _, a := range args {
				if a == obj.BoardID {
					continue Outer
				}
			}

			args = append(args, obj.BoardID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`boards`), qm.WhereIn(`boards.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Board")
	}

	var resultSlice []*Board
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Board")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for boards")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for boards")
	}

	if len(boardsSectionsPositionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Board = foreign
		if foreign.R == nil {
			foreign.R = &boardR{}
		}
		foreign.R.BoardsSectionsPositions = append(foreign.R.BoardsSectionsPositions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BoardID == foreign.ID {
				local.R.Board = foreign
				if foreign.R == nil {
					foreign.R = &boardR{}
				}
				foreign.R.BoardsSectionsPositions = append(foreign.R.BoardsSectionsPositions, local)
				break
			}
		}
	}

	return nil
}

// LoadSection allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (boardsSectionsPositionL) LoadSection(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBoardsSectionsPosition interface{}, mods queries.Applicator) error {
	var slice []*BoardsSectionsPosition
	var object *BoardsSectionsPosition

	if singular {
		object = maybeBoardsSectionsPosition.(*BoardsSectionsPosition)
	} else {
		slice = *maybeBoardsSectionsPosition.(*[]*BoardsSectionsPosition)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &boardsSectionsPositionR{}
		}
		args = append(args, object.SectionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &boardsSectionsPositionR{}
			}

			for _, a := range args {
				if a == obj.SectionID {
					continue Outer
				}
			}

			args = append(args, obj.SectionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`sections`), qm.WhereIn(`sections.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Section")
	}

	var resultSlice []*Section
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Section")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sections")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sections")
	}

	if len(boardsSectionsPositionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Section = foreign
		if foreign.R == nil {
			foreign.R = &sectionR{}
		}
		foreign.R.BoardsSectionsPosition = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SectionID == foreign.ID {
				local.R.Section = foreign
				if foreign.R == nil {
					foreign.R = &sectionR{}
				}
				foreign.R.BoardsSectionsPosition = local
				break
			}
		}
	}

	return nil
}

// SetBoard of the boardsSectionsPosition to the related item.
// Sets o.R.Board to related.
// Adds o to related.R.BoardsSectionsPositions.
func (o *BoardsSectionsPosition) SetBoard(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Board) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `boards_sections_positions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"board_id"}),
		strmangle.WhereClause("`", "`", 0, boardsSectionsPositionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BoardID = related.ID
	if o.R == nil {
		o.R = &boardsSectionsPositionR{
			Board: related,
		}
	} else {
		o.R.Board = related
	}

	if related.R == nil {
		related.R = &boardR{
			BoardsSectionsPositions: BoardsSectionsPositionSlice{o},
		}
	} else {
		related.R.BoardsSectionsPositions = append(related.R.BoardsSectionsPositions, o)
	}

	return nil
}

// SetSection of the boardsSectionsPosition to the related item.
// Sets o.R.Section to related.
// Adds o to related.R.BoardsSectionsPosition.
func (o *BoardsSectionsPosition) SetSection(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Section) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `boards_sections_positions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"section_id"}),
		strmangle.WhereClause("`", "`", 0, boardsSectionsPositionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SectionID = related.ID
	if o.R == nil {
		o.R = &boardsSectionsPositionR{
			Section: related,
		}
	} else {
		o.R.Section = related
	}

	if related.R == nil {
		related.R = &sectionR{
			BoardsSectionsPosition: o,
		}
	} else {
		related.R.BoardsSectionsPosition = o
	}

	return nil
}

// BoardsSectionsPositions retrieves all the records using an executor.
func BoardsSectionsPositions(mods ...qm.QueryMod) boardsSectionsPositionQuery {
	mods = append(mods, qm.From("`boards_sections_positions`"))
	return boardsSectionsPositionQuery{NewQuery(mods...)}
}

// FindBoardsSectionsPosition retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBoardsSectionsPosition(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*BoardsSectionsPosition, error) {
	boardsSectionsPositionObj := &BoardsSectionsPosition{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `boards_sections_positions` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, boardsSectionsPositionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "rdb: unable to select from boards_sections_positions")
	}

	return boardsSectionsPositionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BoardsSectionsPosition) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("rdb: no boards_sections_positions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(boardsSectionsPositionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	boardsSectionsPositionInsertCacheMut.RLock()
	cache, cached := boardsSectionsPositionInsertCache[key]
	boardsSectionsPositionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			boardsSectionsPositionAllColumns,
			boardsSectionsPositionColumnsWithDefault,
			boardsSectionsPositionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `boards_sections_positions` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `boards_sections_positions` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `boards_sections_positions` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, boardsSectionsPositionPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "rdb: unable to insert into boards_sections_positions")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == boardsSectionsPositionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to populate default values for boards_sections_positions")
	}

CacheNoHooks:
	if !cached {
		boardsSectionsPositionInsertCacheMut.Lock()
		boardsSectionsPositionInsertCache[key] = cache
		boardsSectionsPositionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the BoardsSectionsPosition.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BoardsSectionsPosition) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	boardsSectionsPositionUpdateCacheMut.RLock()
	cache, cached := boardsSectionsPositionUpdateCache[key]
	boardsSectionsPositionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			boardsSectionsPositionAllColumns,
			boardsSectionsPositionPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("rdb: unable to update boards_sections_positions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `boards_sections_positions` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, boardsSectionsPositionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, append(wl, boardsSectionsPositionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to update boards_sections_positions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by update for boards_sections_positions")
	}

	if !cached {
		boardsSectionsPositionUpdateCacheMut.Lock()
		boardsSectionsPositionUpdateCache[key] = cache
		boardsSectionsPositionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q boardsSectionsPositionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to update all for boards_sections_positions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to retrieve rows affected for boards_sections_positions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BoardsSectionsPositionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("rdb: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardsSectionsPositionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `boards_sections_positions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, boardsSectionsPositionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to update all in boardsSectionsPosition slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to retrieve rows affected all in update all boardsSectionsPosition")
	}
	return rowsAff, nil
}

var mySQLBoardsSectionsPositionUniqueColumns = []string{
	"id",
	"section_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BoardsSectionsPosition) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("rdb: no boards_sections_positions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(boardsSectionsPositionColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLBoardsSectionsPositionUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	boardsSectionsPositionUpsertCacheMut.RLock()
	cache, cached := boardsSectionsPositionUpsertCache[key]
	boardsSectionsPositionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			boardsSectionsPositionAllColumns,
			boardsSectionsPositionColumnsWithDefault,
			boardsSectionsPositionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			boardsSectionsPositionAllColumns,
			boardsSectionsPositionPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("rdb: unable to upsert boards_sections_positions, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "boards_sections_positions", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `boards_sections_positions` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "rdb: unable to upsert for boards_sections_positions")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == boardsSectionsPositionMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(boardsSectionsPositionType, boardsSectionsPositionMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to retrieve unique values for boards_sections_positions")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to populate default values for boards_sections_positions")
	}

CacheNoHooks:
	if !cached {
		boardsSectionsPositionUpsertCacheMut.Lock()
		boardsSectionsPositionUpsertCache[key] = cache
		boardsSectionsPositionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single BoardsSectionsPosition record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BoardsSectionsPosition) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("rdb: no BoardsSectionsPosition provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), boardsSectionsPositionPrimaryKeyMapping)
	sql := "DELETE FROM `boards_sections_positions` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to delete from boards_sections_positions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by delete for boards_sections_positions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q boardsSectionsPositionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("rdb: no boardsSectionsPositionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to delete all from boards_sections_positions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by deleteall for boards_sections_positions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BoardsSectionsPositionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(boardsSectionsPositionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardsSectionsPositionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `boards_sections_positions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, boardsSectionsPositionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to delete all from boardsSectionsPosition slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by deleteall for boards_sections_positions")
	}

	if len(boardsSectionsPositionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BoardsSectionsPosition) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBoardsSectionsPosition(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BoardsSectionsPositionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BoardsSectionsPositionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), boardsSectionsPositionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `boards_sections_positions`.* FROM `boards_sections_positions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, boardsSectionsPositionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to reload all in BoardsSectionsPositionSlice")
	}

	*o = slice

	return nil
}

// BoardsSectionsPositionExists checks if the BoardsSectionsPosition row exists.
func BoardsSectionsPositionExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `boards_sections_positions` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "rdb: unable to check if boards_sections_positions exists")
	}

	return exists, nil
}
