// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package rdb

var TableNames = struct {
	Boards                  string
	BoardsSectionsPositions string
	Cards                   string
	CardsLabels             string
	Labels                  string
	Sections                string
	SectionsCardsPositions  string
}{
	Boards:                  "boards",
	BoardsSectionsPositions: "boards_sections_positions",
	Cards:                   "cards",
	CardsLabels:             "cards_labels",
	Labels:                  "labels",
	Sections:                "sections",
	SectionsCardsPositions:  "sections_cards_positions",
}
