// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package rdb

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// SectionsCardsPosition is an object representing the database table.
type SectionsCardsPosition struct {
	ID        uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	SectionID uint      `boil:"section_id" json:"section_id" toml:"section_id" yaml:"section_id"`
	CardID    uint      `boil:"card_id" json:"card_id" toml:"card_id" yaml:"card_id"`
	Position  float64   `boil:"position" json:"position" toml:"position" yaml:"position"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *sectionsCardsPositionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sectionsCardsPositionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SectionsCardsPositionColumns = struct {
	ID        string
	SectionID string
	CardID    string
	Position  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	SectionID: "section_id",
	CardID:    "card_id",
	Position:  "position",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

type whereHelperfloat64 struct{ field string }

func (w whereHelperfloat64) EQ(x float64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperfloat64) NEQ(x float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperfloat64) LT(x float64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperfloat64) LTE(x float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperfloat64) GT(x float64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperfloat64) GTE(x float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var SectionsCardsPositionWhere = struct {
	ID        whereHelperuint
	SectionID whereHelperuint
	CardID    whereHelperuint
	Position  whereHelperfloat64
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperuint{field: "`sections_cards_positions`.`id`"},
	SectionID: whereHelperuint{field: "`sections_cards_positions`.`section_id`"},
	CardID:    whereHelperuint{field: "`sections_cards_positions`.`card_id`"},
	Position:  whereHelperfloat64{field: "`sections_cards_positions`.`position`"},
	CreatedAt: whereHelpernull_Time{field: "`sections_cards_positions`.`created_at`"},
	UpdatedAt: whereHelpernull_Time{field: "`sections_cards_positions`.`updated_at`"},
}

// SectionsCardsPositionRels is where relationship names are stored.
var SectionsCardsPositionRels = struct {
	Card    string
	Section string
}{
	Card:    "Card",
	Section: "Section",
}

// sectionsCardsPositionR is where relationships are stored.
type sectionsCardsPositionR struct {
	Card    *Card
	Section *Section
}

// NewStruct creates a new relationship struct
func (*sectionsCardsPositionR) NewStruct() *sectionsCardsPositionR {
	return &sectionsCardsPositionR{}
}

// sectionsCardsPositionL is where Load methods for each relationship are stored.
type sectionsCardsPositionL struct{}

var (
	sectionsCardsPositionAllColumns            = []string{"id", "section_id", "card_id", "position", "created_at", "updated_at"}
	sectionsCardsPositionColumnsWithoutDefault = []string{"section_id", "card_id", "position"}
	sectionsCardsPositionColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	sectionsCardsPositionPrimaryKeyColumns     = []string{"id"}
)

type (
	// SectionsCardsPositionSlice is an alias for a slice of pointers to SectionsCardsPosition.
	// This should generally be used opposed to []SectionsCardsPosition.
	SectionsCardsPositionSlice []*SectionsCardsPosition
	// SectionsCardsPositionHook is the signature for custom SectionsCardsPosition hook methods
	SectionsCardsPositionHook func(context.Context, boil.ContextExecutor, *SectionsCardsPosition) error

	sectionsCardsPositionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sectionsCardsPositionType                 = reflect.TypeOf(&SectionsCardsPosition{})
	sectionsCardsPositionMapping              = queries.MakeStructMapping(sectionsCardsPositionType)
	sectionsCardsPositionPrimaryKeyMapping, _ = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, sectionsCardsPositionPrimaryKeyColumns)
	sectionsCardsPositionInsertCacheMut       sync.RWMutex
	sectionsCardsPositionInsertCache          = make(map[string]insertCache)
	sectionsCardsPositionUpdateCacheMut       sync.RWMutex
	sectionsCardsPositionUpdateCache          = make(map[string]updateCache)
	sectionsCardsPositionUpsertCacheMut       sync.RWMutex
	sectionsCardsPositionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sectionsCardsPositionBeforeInsertHooks []SectionsCardsPositionHook
var sectionsCardsPositionBeforeUpdateHooks []SectionsCardsPositionHook
var sectionsCardsPositionBeforeDeleteHooks []SectionsCardsPositionHook
var sectionsCardsPositionBeforeUpsertHooks []SectionsCardsPositionHook

var sectionsCardsPositionAfterInsertHooks []SectionsCardsPositionHook
var sectionsCardsPositionAfterSelectHooks []SectionsCardsPositionHook
var sectionsCardsPositionAfterUpdateHooks []SectionsCardsPositionHook
var sectionsCardsPositionAfterDeleteHooks []SectionsCardsPositionHook
var sectionsCardsPositionAfterUpsertHooks []SectionsCardsPositionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SectionsCardsPosition) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SectionsCardsPosition) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SectionsCardsPosition) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SectionsCardsPosition) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SectionsCardsPosition) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SectionsCardsPosition) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SectionsCardsPosition) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SectionsCardsPosition) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SectionsCardsPosition) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sectionsCardsPositionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSectionsCardsPositionHook registers your hook function for all future operations.
func AddSectionsCardsPositionHook(hookPoint boil.HookPoint, sectionsCardsPositionHook SectionsCardsPositionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		sectionsCardsPositionBeforeInsertHooks = append(sectionsCardsPositionBeforeInsertHooks, sectionsCardsPositionHook)
	case boil.BeforeUpdateHook:
		sectionsCardsPositionBeforeUpdateHooks = append(sectionsCardsPositionBeforeUpdateHooks, sectionsCardsPositionHook)
	case boil.BeforeDeleteHook:
		sectionsCardsPositionBeforeDeleteHooks = append(sectionsCardsPositionBeforeDeleteHooks, sectionsCardsPositionHook)
	case boil.BeforeUpsertHook:
		sectionsCardsPositionBeforeUpsertHooks = append(sectionsCardsPositionBeforeUpsertHooks, sectionsCardsPositionHook)
	case boil.AfterInsertHook:
		sectionsCardsPositionAfterInsertHooks = append(sectionsCardsPositionAfterInsertHooks, sectionsCardsPositionHook)
	case boil.AfterSelectHook:
		sectionsCardsPositionAfterSelectHooks = append(sectionsCardsPositionAfterSelectHooks, sectionsCardsPositionHook)
	case boil.AfterUpdateHook:
		sectionsCardsPositionAfterUpdateHooks = append(sectionsCardsPositionAfterUpdateHooks, sectionsCardsPositionHook)
	case boil.AfterDeleteHook:
		sectionsCardsPositionAfterDeleteHooks = append(sectionsCardsPositionAfterDeleteHooks, sectionsCardsPositionHook)
	case boil.AfterUpsertHook:
		sectionsCardsPositionAfterUpsertHooks = append(sectionsCardsPositionAfterUpsertHooks, sectionsCardsPositionHook)
	}
}

// One returns a single sectionsCardsPosition record from the query.
func (q sectionsCardsPositionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SectionsCardsPosition, error) {
	o := &SectionsCardsPosition{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "rdb: failed to execute a one query for sections_cards_positions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SectionsCardsPosition records from the query.
func (q sectionsCardsPositionQuery) All(ctx context.Context, exec boil.ContextExecutor) (SectionsCardsPositionSlice, error) {
	var o []*SectionsCardsPosition

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "rdb: failed to assign all query results to SectionsCardsPosition slice")
	}

	if len(sectionsCardsPositionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SectionsCardsPosition records in the query.
func (q sectionsCardsPositionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to count sections_cards_positions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sectionsCardsPositionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "rdb: failed to check if sections_cards_positions exists")
	}

	return count > 0, nil
}

// Card pointed to by the foreign key.
func (o *SectionsCardsPosition) Card(mods ...qm.QueryMod) cardQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CardID),
	}

	queryMods = append(queryMods, mods...)

	query := Cards(queryMods...)
	queries.SetFrom(query.Query, "`cards`")

	return query
}

// Section pointed to by the foreign key.
func (o *SectionsCardsPosition) Section(mods ...qm.QueryMod) sectionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.SectionID),
	}

	queryMods = append(queryMods, mods...)

	query := Sections(queryMods...)
	queries.SetFrom(query.Query, "`sections`")

	return query
}

// LoadCard allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sectionsCardsPositionL) LoadCard(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSectionsCardsPosition interface{}, mods queries.Applicator) error {
	var slice []*SectionsCardsPosition
	var object *SectionsCardsPosition

	if singular {
		object = maybeSectionsCardsPosition.(*SectionsCardsPosition)
	} else {
		slice = *maybeSectionsCardsPosition.(*[]*SectionsCardsPosition)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &sectionsCardsPositionR{}
		}
		args = append(args, object.CardID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sectionsCardsPositionR{}
			}

			for _, a := range args {
				if a == obj.CardID {
					continue Outer
				}
			}

			args = append(args, obj.CardID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`cards`), qm.WhereIn(`cards.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Card")
	}

	var resultSlice []*Card
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Card")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for cards")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for cards")
	}

	if len(sectionsCardsPositionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Card = foreign
		if foreign.R == nil {
			foreign.R = &cardR{}
		}
		foreign.R.SectionsCardsPosition = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CardID == foreign.ID {
				local.R.Card = foreign
				if foreign.R == nil {
					foreign.R = &cardR{}
				}
				foreign.R.SectionsCardsPosition = local
				break
			}
		}
	}

	return nil
}

// LoadSection allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sectionsCardsPositionL) LoadSection(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSectionsCardsPosition interface{}, mods queries.Applicator) error {
	var slice []*SectionsCardsPosition
	var object *SectionsCardsPosition

	if singular {
		object = maybeSectionsCardsPosition.(*SectionsCardsPosition)
	} else {
		slice = *maybeSectionsCardsPosition.(*[]*SectionsCardsPosition)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &sectionsCardsPositionR{}
		}
		args = append(args, object.SectionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sectionsCardsPositionR{}
			}

			for _, a := range args {
				if a == obj.SectionID {
					continue Outer
				}
			}

			args = append(args, obj.SectionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`sections`), qm.WhereIn(`sections.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Section")
	}

	var resultSlice []*Section
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Section")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sections")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sections")
	}

	if len(sectionsCardsPositionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Section = foreign
		if foreign.R == nil {
			foreign.R = &sectionR{}
		}
		foreign.R.SectionsCardsPositions = append(foreign.R.SectionsCardsPositions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SectionID == foreign.ID {
				local.R.Section = foreign
				if foreign.R == nil {
					foreign.R = &sectionR{}
				}
				foreign.R.SectionsCardsPositions = append(foreign.R.SectionsCardsPositions, local)
				break
			}
		}
	}

	return nil
}

// SetCard of the sectionsCardsPosition to the related item.
// Sets o.R.Card to related.
// Adds o to related.R.SectionsCardsPosition.
func (o *SectionsCardsPosition) SetCard(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Card) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sections_cards_positions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"card_id"}),
		strmangle.WhereClause("`", "`", 0, sectionsCardsPositionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CardID = related.ID
	if o.R == nil {
		o.R = &sectionsCardsPositionR{
			Card: related,
		}
	} else {
		o.R.Card = related
	}

	if related.R == nil {
		related.R = &cardR{
			SectionsCardsPosition: o,
		}
	} else {
		related.R.SectionsCardsPosition = o
	}

	return nil
}

// SetSection of the sectionsCardsPosition to the related item.
// Sets o.R.Section to related.
// Adds o to related.R.SectionsCardsPositions.
func (o *SectionsCardsPosition) SetSection(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Section) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sections_cards_positions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"section_id"}),
		strmangle.WhereClause("`", "`", 0, sectionsCardsPositionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SectionID = related.ID
	if o.R == nil {
		o.R = &sectionsCardsPositionR{
			Section: related,
		}
	} else {
		o.R.Section = related
	}

	if related.R == nil {
		related.R = &sectionR{
			SectionsCardsPositions: SectionsCardsPositionSlice{o},
		}
	} else {
		related.R.SectionsCardsPositions = append(related.R.SectionsCardsPositions, o)
	}

	return nil
}

// SectionsCardsPositions retrieves all the records using an executor.
func SectionsCardsPositions(mods ...qm.QueryMod) sectionsCardsPositionQuery {
	mods = append(mods, qm.From("`sections_cards_positions`"))
	return sectionsCardsPositionQuery{NewQuery(mods...)}
}

// FindSectionsCardsPosition retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSectionsCardsPosition(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*SectionsCardsPosition, error) {
	sectionsCardsPositionObj := &SectionsCardsPosition{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `sections_cards_positions` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, sectionsCardsPositionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "rdb: unable to select from sections_cards_positions")
	}

	return sectionsCardsPositionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SectionsCardsPosition) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("rdb: no sections_cards_positions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sectionsCardsPositionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sectionsCardsPositionInsertCacheMut.RLock()
	cache, cached := sectionsCardsPositionInsertCache[key]
	sectionsCardsPositionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sectionsCardsPositionAllColumns,
			sectionsCardsPositionColumnsWithDefault,
			sectionsCardsPositionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `sections_cards_positions` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `sections_cards_positions` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `sections_cards_positions` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, sectionsCardsPositionPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "rdb: unable to insert into sections_cards_positions")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == sectionsCardsPositionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to populate default values for sections_cards_positions")
	}

CacheNoHooks:
	if !cached {
		sectionsCardsPositionInsertCacheMut.Lock()
		sectionsCardsPositionInsertCache[key] = cache
		sectionsCardsPositionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SectionsCardsPosition.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SectionsCardsPosition) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sectionsCardsPositionUpdateCacheMut.RLock()
	cache, cached := sectionsCardsPositionUpdateCache[key]
	sectionsCardsPositionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sectionsCardsPositionAllColumns,
			sectionsCardsPositionPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("rdb: unable to update sections_cards_positions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `sections_cards_positions` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, sectionsCardsPositionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, append(wl, sectionsCardsPositionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to update sections_cards_positions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by update for sections_cards_positions")
	}

	if !cached {
		sectionsCardsPositionUpdateCacheMut.Lock()
		sectionsCardsPositionUpdateCache[key] = cache
		sectionsCardsPositionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sectionsCardsPositionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to update all for sections_cards_positions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to retrieve rows affected for sections_cards_positions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SectionsCardsPositionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("rdb: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sectionsCardsPositionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `sections_cards_positions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sectionsCardsPositionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to update all in sectionsCardsPosition slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to retrieve rows affected all in update all sectionsCardsPosition")
	}
	return rowsAff, nil
}

var mySQLSectionsCardsPositionUniqueColumns = []string{
	"id",
	"card_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SectionsCardsPosition) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("rdb: no sections_cards_positions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sectionsCardsPositionColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSectionsCardsPositionUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sectionsCardsPositionUpsertCacheMut.RLock()
	cache, cached := sectionsCardsPositionUpsertCache[key]
	sectionsCardsPositionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			sectionsCardsPositionAllColumns,
			sectionsCardsPositionColumnsWithDefault,
			sectionsCardsPositionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			sectionsCardsPositionAllColumns,
			sectionsCardsPositionPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("rdb: unable to upsert sections_cards_positions, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "sections_cards_positions", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `sections_cards_positions` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "rdb: unable to upsert for sections_cards_positions")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == sectionsCardsPositionMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(sectionsCardsPositionType, sectionsCardsPositionMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to retrieve unique values for sections_cards_positions")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to populate default values for sections_cards_positions")
	}

CacheNoHooks:
	if !cached {
		sectionsCardsPositionUpsertCacheMut.Lock()
		sectionsCardsPositionUpsertCache[key] = cache
		sectionsCardsPositionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SectionsCardsPosition record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SectionsCardsPosition) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("rdb: no SectionsCardsPosition provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sectionsCardsPositionPrimaryKeyMapping)
	sql := "DELETE FROM `sections_cards_positions` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to delete from sections_cards_positions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by delete for sections_cards_positions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sectionsCardsPositionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("rdb: no sectionsCardsPositionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to delete all from sections_cards_positions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by deleteall for sections_cards_positions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SectionsCardsPositionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sectionsCardsPositionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sectionsCardsPositionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `sections_cards_positions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sectionsCardsPositionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "rdb: unable to delete all from sectionsCardsPosition slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "rdb: failed to get rows affected by deleteall for sections_cards_positions")
	}

	if len(sectionsCardsPositionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SectionsCardsPosition) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSectionsCardsPosition(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SectionsCardsPositionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SectionsCardsPositionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sectionsCardsPositionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `sections_cards_positions`.* FROM `sections_cards_positions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sectionsCardsPositionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "rdb: unable to reload all in SectionsCardsPositionSlice")
	}

	*o = slice

	return nil
}

// SectionsCardsPositionExists checks if the SectionsCardsPosition row exists.
func SectionsCardsPositionExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `sections_cards_positions` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "rdb: unable to check if sections_cards_positions exists")
	}

	return exists, nil
}
