version: '3.7'

services:
  api:
    image: plank_dev
    build:
      context: ../../
      dockerfile: ./deployments/development/api/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ../../:/plank
    depends_on:
      - db
    environment:
      MYSQL_DBNAME: plank_dev
      MYSQL_USER: plank_dev
      MYSQL_PASS: plank_dev
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_SKIPSQLCMD: 'true'
      MYSQL_SSLMODE: 'false'
      ES_URL: 'http://elasticsearch:9200'
      S3_BUCKET_NAME: 'plank_dev'
      S3_ACCESS_KEY: 'example_access_key'
      S3_SECRET_KEY: 'example_secret_key'
      S3_REGION: 'example_region'
      S3_ENDPOINT: 'http://minio:9000'
      S3_ENDPOINT_EXTERNAL: 'http://localhost:9000'
      REDIS_ADDRESS: 'redis:6379'
      REDIS_PASSWORD: ''
  db:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: plank_dev
      MYSQL_USER: plank_dev
      MYSQL_PASSWORD: plank_dev
      MYSQL_ROOT_PASSWORD: plank_dev
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ../../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - '3306:3306'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - plank_dev_es:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    volumes:
      - plank_dev_s3:/export
    entrypoint: sh
    command: -c 'mkdir -p /export/plank_dev && /usr/bin/minio server /export'
    environment:
      MINIO_ACCESS_KEY: example_access_key
      MINIO_SECRET_KEY: example_secret_key
      MINIO_REGION: example_region
  redis:
    image: 'redis:6.0.8-alpine'
    ports:
      - '6379:6379'
volumes:
  plank_dev_data:
    driver: local
  plank_dev_es:
    driver: local
  plank_dev_s3:
    driver: local
